- name: Configure external volume for /srv
  block:
    - name: Partition mirror volume
      community.general.parted:
        device: '{{ srv_volume_disk_device }}'
        number: 1
        label: gpt
        fs_type: xfs
        part_start: '0%'
        part_end: '100%'
        state: present

    - name: Create XFS filesystem on mirror volume
      community.general.filesystem:
        dev: '{{ srv_volume_part_device }}'
        fstype: xfs

    - name: Mount mirror volume
      ansible.posix.mount:
        src: '{{ srv_volume_part_device }}'
        path: '/srv'
        state: mounted
        fstype: xfs
        opts: defaults
        passno: '2'
        boot: true
  when: use_external_srv_volume
  tags: [storage]

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    update_cache: true

- name: Create docroot
  ansible.builtin.file:
    path: '/srv/www/current'
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  notify: docroot-selinux

- name: nginx running
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Register systemd service fact
  ansible.builtin.service_facts:
  tags: [firewalld]

- name: Open HTTP(S) port(s)
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  # The test box I was developing on had firewalld enabled, but the version I booted from a cloud
  # image in OpenStack didn't even have it installed, maybe because it's expected that the cloud
  # provider will handle those sorts of rules outside the host? Not sure.
  when: "'firewalld.service' in ansible_facts.services and ansible_facts.services['firewalld.service'].state == 'running'"
  loop: "{{ firewalld_http_services }}"
  tags: [firewalld]

- name: Nginx config
  ansible.builtin.template:
    src: '{{ nginx_config_file }}'
    dest: '/etc/nginx/conf.d/rhel-mirror.conf'
    owner: root
    group: root
    mode: '0644'
  register: nginx_config
  notify: restart-nginx
  tags: [https]

- name: HTTPS certs
  block:
    - name: Cert directories
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: '0700'
      loop:
        - '/etc/pki/nginx'
        - '/etc/pki/nginx/private'
      notify: restart-nginx

    - name: Install certs
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: root
        group: root
        mode: '0600'
      loop:
        - { src: '{{ nginx_full_bundle_https_cert }}', dest: '/etc/pki/nginx/server.crt'}
        - { src: '{{ nginx_private_server_https_key }}', dest: '/etc/pki/nginx/private/server.key'}
      notify:
        - certs-selinux
        - restart-nginx
      register: nginx_certs
  when: use_https
  tags: [https]

- name: Add repo file
  ansible.builtin.template:
    src: 'templates/rhel.repo.tpl'
    dest: '/srv/www/current/rhel.repo'
    owner: nginx
    group: nginx
    mode: '0644'
  tags: [repo]
